### ISSUE TITLE
File not Found exception 

### ISSUE THREAD

**Issue by Joe-Mobarak** [mohamedbassel24/OCR-for-Arabic-Scripts#2]
Hey man 
I have a question in NN_classifier.py 
you are loading output3
net.load_state_dict(torch.load("output3"))
What is output3?

**Comment by Khalifa1997** [comment]
@Joe-Mobarak-WoLf It's our own trained model after we had trained it on the cloud and saved it, I would suggest you read the docs on how to save a model, using the command `pickle` could be quite intutive aswell

**Comment by Joe-Mobarak** [comment]
I just want to test the code to be honest 
Because it seems interesting 
So you are telling me i cant do that

**Comment by Khalifa1997** [comment]
As I said, I trained the model on the cloud, to be loaded locally,
a quick google search, https://pytorch.org/tutorials/beginner/saving_loading_models.html

Good luck

**Comment by Joe-Mobarak** [comment]
Well to be honest we are looking for candidates for a PHD program and we are testing your code
It looks good but i didn't understand every part  
specially that loading saving models using pytorch

**Comment by Khalifa1997** [comment]
A google search would save me and you a ton of effort :)

**Comment by Joe-Mobarak** [comment]
So i have to train a classifier 
well i wish i have time man 
If we are gonna work on every project to test it , it is gonna be hell

**Comment by Khalifa1997** [comment]
Fair enough, come back if you need anything!

**Comment by mohamedbassel24** [comment]
Don’t forget to make a star and follow <3

**Comment by Joe-Mobarak** [comment]
Well i was disappointed
i couldn't even run your code 
You should consider posting a test module and you will have more than a star :)
